# Generated by Django 5.1.8 on 2025-04-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageVisits',
            new_name='PageVisit',
        ),
    ]
